config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end
  root 'home#index'
  get '/public_recipes', to: 'home#index'
  resources :food
  resources :recipes do
    resources :recipe_food
    resources :shopping_list
  end 

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
  has_many :recipes, through: :recipe_food, dependent: :destroy

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal: 0 }
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.create!(food_params.merge(user: current_user))

    if @food.save
      redirect_to food_index_path, notice: 'Food added successfully.'
    else
      render new, alert: 'Operation failed.'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    redirect_to food_index_path, notice: 'Food deleted successfully'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/food_helper.rb
module FoodHelper
end

app/views/food/index.html.erb
<div class='mt-5'>
  <h1>Food page</h1>
</div>
<%render partial: "partials/alert"%>
<div class="d-flex md-1 justify-content-end"><%= link_to "Add food", new_food_path, class: "btn btn-outline-primary"%></div><br />
<% if @foods.size.positive? %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement Unit (E.g Kg)</th>
        <th scope="col">Unit Price (E.g, USD)</th>
        <th scope="col">Quantity (available Qtty)</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <%currency = "USD"%>
        <tr>
          <td><%=food.name%></td>
          <td><%=food.measurement_unit%></td>
          <td><%=food.price%></td>
          <td><%=food.quantity%><%=  food.measurement_unit%></td>
          <td>
            <% if can? :destroy, food %>
              <%= button_to food_path(food), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" do %>
                Delete
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No food available</p>
<% end %>

app/views/food/new.html.erb
<h1 class='mt-3'>Add Food</h1>
<%=form_with model: @food, url: food_index_path, method: :post do |f| %>
  <div class="mb-3">
    <%=f.label :name, class:"form-label"%>
    <%=f.text_field :name, class:"form-control"%>
  </div>
  <div class="mb-3">
    <%=f.label :measurement_unit, class:"form-label"%>
    <%=f.text_field :measurement_unit, class:"form-control"%>
  </div>
  <div class="mb-3">
    <%=f.label :price, class:"form-label"%>
    <%=f.number_field :price, class:"form-control"%>
  </div>
  <div class="mb-3">
    <%=f.label :quantity, class:"form-label"%>
    <%=f.number_field :quantity, class:"form-control"%>
  </div>
  <div class="mb-3">
    <%=f.submit "Add Food", class:"form-control alert alert-primary"%>
  </div>
<%end%>