config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end
  root 'home#index'
  get '/public_recipes', to: 'home#index'
  resources :food
  resources :recipes do
    resources :recipe_food
    resources :shopping_list
  end 

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
  has_many :foods, through: :recipe_food, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create!(recipe_params.merge(user: current_user))
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    # RecipeFood.where(recipe_id: @recipe.id).destroy_all
    @recipe.destroy!
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public, :current_user)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class='d-flex section-title justify-content-start'><h1>My Recipes</h1></div>
<div class='d-flex justify-content-end'>
    <%= button_to new_recipe_path, method: :get, class: 'btn btn-outline-primary text-right' do %>
        Create a new Recipe
    <% end %>
</div>
<% if @recipes.empty?%>
    <p class='text-center my-5'>There is no recipe created by you</p>
<% end %>
<div class='recipes-container'>
    <%= render partial: 'partials/recipe', collection: @recipes %>
</div>

app/views/recipes/new.html.erb
<div class='d-flex flex-column'>
    <h1 class="mt-5">Create a new Recipe</h1>
    <div class='d-flex flex-column justify-center'>
        <%= form_with url: recipes_path, method: :post, model: @recipe, class: "mt-5" do |f| %>
        <div class="mb-4 d-flex flex-column">
            <%= f.label 'Name:'%>
            <%= f.text_field 'name', class: 'form-control'%>
        </div>
        <div class="mb-4 d-flex flex-column">
            <%= f.label 'Description:'%>
            <%= f.text_area 'description', class: 'form-control'%>
        </div>
        <div class="mb-4 d-flex flex-column">
            <%= f.label 'Preparation time:'%>
            <%= f.text_field 'preparation_time', class: 'form-control'%>
        </div>
        <div class="mb-4 d-flex flex-column">
            <%= f.label 'Cooking time:'%>
            <%= f.text_field 'cooking_time', class: 'form-control'%>
        </div>
        <div class="mb-4 d-flex flex-column form-check form-switch switch-slider">
            <%= f.check_box 'public', class: 'form-check-input', id: 'public-switch' %>
            <%= f.label 'Make it Public', class: 'form-check-label', for: 'public-switch' %>
        </div>
        <%= f.submit 'Create', class: 'btn btn-primary'%>
        <% end %>
    </div>
</div>

app/views/recipes/show.html.erb
<h1 class='text-center mt-4'><%= @recipe.name %></h1>
<div class='d-flex flex-column fs-1'>
    <p>Preparation time: <%= @recipe.preparation_time%></p>
    <p>Cooking time: <%= @recipe.cooking_time%></p>
</div>
<div>
  <h1>Steps Go Here</h1>
</div>
<p class='text-right'><%= link_to "Generate shopping list", recipe_shopping_list_index_path(@recipe) %></p>
<p class='text-right'><%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe) %></p>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_food.each do |ingred| %>
      <tr>
        <td><%=ingred.food.name%></td>
        <td><%=ingred.quantity%> <%= ingred.food.measurement_unit %> </td>
        <td><%=number_to_currency(ingred.food.price * ingred.quantity) %></td>
        <td>
          <% if can? :destroy, @recipe %>
            <%= button_to recipe_recipe_food_path(@recipe, ingred), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' do %>
              Delete
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>