config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end
  root 'home#index'
  get '/public_recipes', to: 'home#index'
  resources :food
  resources :recipes do
    resources :recipe_food
    resources :shopping_list
  end 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    # A registered user or a new user
    user ||= User.new
    can :read, :all
    #   # admins have the privilege to manage everything
    return unless user.present?

    # a user can manage their own foods, recipes, and recipe_foods
    can(:manage, Food, user:)
    can :manage, Recipe, user_id: user.id
    can :manage, RecipeFood, user_id: user.id
    return unless user.is? :admin

    can :manage, :all

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
  has_many :recipes, through: :recipe_food, dependent: :destroy

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
  has_many :foods, through: :recipe_food, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :public, inclusion: { in: [true, false] }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, foreign_key: 'food_id'
  belongs_to :recipe, foreign_key: 'recipe_id'

  validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 1000 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :recipes
  has_many :foods

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  layout 'application'

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.create!(food_params.merge(user: current_user))

    if @food.save
      redirect_to food_index_path, notice: 'Food added successfully.'
    else
      render new, alert: 'Operation failed.'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    redirect_to food_index_path, notice: 'Food deleted successfully'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @publicrecipes = Recipe.where(public: true).order('created_at DESC')
  end
end

app/controllers/recipe_food_controller.rb
class RecipeFoodController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @foods = current_user.foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @food = Food.find(params[:recipe_food][:food])
    @recipe_food = RecipeFood.new(recipe: @recipe, food: @food, quantity: params[:recipe_food][:quantity])

    if @recipe_food.save
      redirect_to @recipe, notice: 'Ingredient was successfully added.'
    else
      render :new, alert: "Couldn't add Ingredient to your recipe"
    end
  end

  def destroy
    @ingredient = RecipeFood.find(params[:id])
    @ingredient.destroy

    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def recipe_params
    params.require(:recipe_food).permit(:food, :quantity, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create!(recipe_params.merge(user: current_user))
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    # RecipeFood.where(recipe_id: @recipe.id).destroy_all
    @recipe.destroy!
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public, :current_user)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = @recipe.recipe_food.includes([:food])
    @total = sum_total(@recipe_foods)
  end

  def sum_total(recipe_foods)
    total = 0
    recipe_foods.each do |item|
      total += item.food.price * item.quantity.to_i
    end
    total
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TastyTrek</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,500;0,700;0,900;0,1000;1,300;1,500;1,1000&family=Tourney:ital,wght@0,200;0,300;0,500;1,100&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bad+Script&family=Gafata&family=Gruppo&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1b6d3052e7.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: 'partials/navbar'%>
    <%= render partial: 'partials/alert'%>
    <div class='container'>
      <%= yield %>
    </div>
    <% if current_user %>
      <div class='signedin-bg'></div>
    <%end%>
  </body>
</html>

app/views/partials/_alert.html.erb
<%if notice%>
  <div class="alert alert-success" role="alert">
    <p class="notice text-center text-white"><%= notice %></p>
  </div>
<%end%>
<%if alert%>
  <div class="alert alert-danger" role="alert">
    <p class="alert text-center text-white"><%= alert %></p>
  </div>
<%end%>

app/views/partials/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
    <div>
      <i class="fa-regular fa-bowl-food"></i>
      <a class="navbar-brand logo" href="#">Tasty Trek</a>
    </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Foods', food_index_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Recipes', root_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'About Us', root_path, class: "nav-link"%>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/_navbar.html.erb
<nav class="d-md-flex flex-nowrap px-2 align-content-center navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <div class="d-flex flex-row gap-2">
    <a class="navbar-brand logo fw-md-light" href="#">Tasty Trek</a>
  </div>
  <div class="me-md-2 navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon p-2"></span>
  </div>
  <div class="collapse navbar-collapse justify-content-end" id="navbarText">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to 'Public Recipes', public_recipes_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Foods', food_index_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'My Recipes', recipes_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'About Us', public_recipes_path, class: "nav-link"%>
      </li>
      <% if user_signed_in? %>
        <span class='navbar-text border border-success mx-3 px-2 rounded'>Signed in as, <%= current_user.name%></span>
      <li class="nav-item d-flex justify-center">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-success mx-1 pb-0 pt-2"%>
      </li>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-success mx-2 pb-0 pt-2" %> 
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-success mx-2 pt-2" %>
      <%end%>
    </ul>
  </div>
</nav>

app/views/partials/_publicrecipe.html.erb
<div class='recipe-card d-flex flex-column justify-content-around py-2 mt-2 mb-2'>
    <div class='d-flex flex-row justify-content-around align-items-baseline'>
        <div>
            <%= link_to publicrecipe.name, recipe_path(publicrecipe), class: 'recipe-title'%>
            <p class='text-secondary'>Total food Items: <%= publicrecipe.foods.count%></p> 
            <% sum = 0 %>
            <% publicrecipe.recipe_food.each do |item| %>
            <% sum += (item.food.price * item.quantity)%>
            <%end%>   
            <p class='text-secondary'>Total Price: <%= sum %></p>    
        </div>
        <p class='placeholder w-50'><%= publicrecipe.description%></p>
    </div>
    <div class='d-flex justify-content-center recipe-card-options'>
        <% if can? :destroy, publicrecipe%>
            <%= button_to recipe_path(publicrecipe.id), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: 'btn btn-danger' do %>                    Delete
            <% end %>
        <%end%>
        <p class='text-primary'>Recipe created By: <%= publicrecipe.user.name%></p>    
    </div>
</div>

app/views/partials/_recipe.html.erb
<div class='recipe-card d-flex flex-column justify-content-around py-3 mt-5 mb-5'>
    <div class='d-flex flex-row justify-content-around align-items-baseline'>
        <%= link_to recipe.name, recipe_path(recipe), class: 'recipe-title'%>
        <p class='placeholder w-50'><%= recipe.description%></p>
    </div>
    <div class='d-flex justify-content-start recipe-card-options'>
            <% if can? :destroy, recipe%>
                <%= button_to recipe_path(recipe.id), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: 'btn btn-danger' do %>
                    Delete
                <% end %>
            <%end%>
            <%# <p class='text-primary'>This Recipe By: <%= recipe.user.name%>
        </div>
</div>