config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end
  root 'home#index'
  get '/public_recipes', to: 'home#index'
  resources :food
  resources :recipes do
    resources :recipe_food
    resources :shopping_list
  end 

end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, foreign_key: 'food_id'
  belongs_to :recipe, foreign_key: 'recipe_id'

  validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 1000 }
end

app/controllers/recipe_food_controller.rb
class RecipeFoodController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @foods = current_user.foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @food = Food.find(params[:recipe_food][:food])
    @recipe_food = RecipeFood.new(recipe: @recipe, food: @food, quantity: params[:recipe_food][:quantity])

    if @recipe_food.save
      redirect_to @recipe, notice: 'Ingredient was successfully added.'
    else
      render :new, alert: "Couldn't add Ingredient to your recipe"
    end
  end

  def destroy
    @ingredient = RecipeFood.find(params[:id])
    @ingredient.destroy

    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def recipe_params
    params.require(:recipe_food).permit(:food, :quantity, :recipe_id)
  end
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/views/recipe_food/new.html.erb
<div class='d-flex flex-column'>
    <h1 class="mt-5">Add Ingrediant</h1>
    <div class='d-flex flex-column justify-center'>
        <%= form_with url: recipe_recipe_food_index_path, method: :post, model: @recipe_food, class: "mt-5" do |f| %>
        <div class="mb-4 d-flex flex-column">
            <%= f.label :Ingrediant %>
            <%= f.select :food, options_for_select(@foods.map { |f| [f.name, f.id] }) %>
        </div>
        <div class="mb-4 d-flex flex-column">
            <%= f.label :Quantity %>
            <%= f.number_field :quantity %>
        </div>
        <%= f.submit 'Add', class: 'btn btn-primary'%>
        <% end %>
    </div>
</div>